# Configuration for https://goreleaser.com/
project_name: packer-provisioner-serverspec

builds:
  - id: packer-provisioner-serverspec
    binary: packer-provisioner-serverspec
    main: main.go
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    env:
      - CGO_ENABLED=0

archives:
  - id: packer-provisioner-serverspec
    builds: [ packer-provisioner-serverspec ]
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: 386
      amd64: amd64
    files:
      - none*
